CREATE DATABASE IF NOT EXISTS utp_evalua CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE utp_evalua;

CREATE TABLE IF NOT EXISTS facultades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carreras (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(140) NOT NULL,
  facultad_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_carrera_facultad UNIQUE (nombre, facultad_id),
  CONSTRAINT fk_carrera_facultad FOREIGN KEY (facultad_id) REFERENCES facultades(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cursos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(140) NOT NULL,
  codigo VARCHAR(40),
  creditos INT DEFAULT 3,
  carrera_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_curso_carrera UNIQUE (nombre, carrera_id),
  CONSTRAINT fk_curso_carrera FOREIGN KEY (carrera_id) REFERENCES carreras(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS estudiantes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombres VARCHAR(120) NOT NULL,
  correo VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'Estudiante',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS docentes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombres VARCHAR(120) NOT NULL,
  apellidos VARCHAR(120) NOT NULL,
  correo VARCHAR(160) NOT NULL UNIQUE,
  fotografia VARCHAR(255),
  facultad_id INT NOT NULL,
  carrera_id INT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_docente_facultad FOREIGN KEY (facultad_id) REFERENCES facultades(id),
  CONSTRAINT fk_docente_carrera FOREIGN KEY (carrera_id) REFERENCES carreras(id)
);

CREATE TABLE IF NOT EXISTS resenas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  docente_id INT NOT NULL,
  estudiante_id INT NOT NULL,
  calificacion INT NOT NULL,
  comentario TEXT NOT NULL,
  fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado VARCHAR(20) NOT NULL DEFAULT 'visible',
  motivo_reporte VARCHAR(255),
  fecha_reporte DATETIME,
  reportado_por_id INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT ck_rating_range CHECK (calificacion >= 1 AND calificacion <= 5),
  CONSTRAINT uq_resena_estudiante_docente UNIQUE (docente_id, estudiante_id),
  CONSTRAINT fk_resena_docente FOREIGN KEY (docente_id) REFERENCES docentes(id) ON DELETE CASCADE,
  CONSTRAINT fk_resena_estudiante FOREIGN KEY (estudiante_id) REFERENCES estudiantes(id) ON DELETE CASCADE,
  CONSTRAINT fk_resena_reportado_por FOREIGN KEY (reportado_por_id) REFERENCES estudiantes(id) ON DELETE SET NULL
);
